#!/bin/sh


wget -O archive.tar.gz https://github.com/kaytrance/nembo/archive/1.0.0.tar.gz &&

tar -zxvf --strip-components=1 archive.tar.gz &&

rm archive.tar.gz &&
rm .gitignore &&

npm init &&
bower init &&
gulp init &&

echo "All done!"