#!/bin/sh


wget -O archive.tar.gz https://github.com/kaytrance/nembo/archive/1.0.0.tar.gz &&

tar -zxvf archive.tar.gz --strip-components=1 &&

rm archive.tar.gz &&
rm .gitignore &&

npm install &&
bower install &&
gulp init &&

echo "All done!"